### ISSUE TITLE
Add back Xfce/XUbuntu session

### ISSUE THREAD

**Issue by cat-master21** [rhino-linux/os#57]
Currently, the generic XFCE session is not available https://github.com/rhino-linux/os/blob/58b20084cb0e6ea1811aa72f7916f725c2352857/etc/config/hooks/live/099-install-custom-apps.chroot#L224 Now that Unicorn has been updated to use it's own start file `startunicorn`, the Xfce seesion can now be added back.

**Comment by oklopfer** [comment]
Thats not why this was done. It was done because launching an XFCE session or Xubuntu session will just launch a unicorn session but claim that it is one of the others - because all 3 of them, under the hood, are still just XFCE, so they all end up reading from the same user config files. Unicorn is meant to be a full replacement of both sessions, so we hide them completely.

**Comment by cat-master21** [comment]
Okay then, I will change the description to relfect this @oklopfer but now that unicorn has a new start file (`startunicorn`) this should be possible now I think.

**Comment by oklopfer** [comment]
No, startunicorn just makes it work faster. We cant drop in configs like how we wanted to. It still remains being ~/.config/xfce4

**Comment by oklopfer** [comment]
What I mean is that XFCE uses abysmal and slow /bin/sh, we updated it to /bin/bash and it is definitely faster
